# -*- coding: utf-8 -*-
# English content for the /en/ tree. First-pass translation of the whole
# site (chrome + all 38 texts + manifesto + CV + projects), generated in
# one batch per the site owner's decision (orgculture-archive README,
# "Английская версия сайта"). Keys mirror gen.py's TEXTS / MANIFESTO_POINTS
# / CV_ROLES / PROJECTS one-to-one by slug/order, so gen_en.py can zip them
# with the Russian originals for image/link/slug/order data it doesn't
# need to duplicate. Voice-sensitive — meant to be reviewed and adjusted
# by the author, not treated as final.

TAG_EN = {
    "фильм": "film",
    "спектакль": "show",
    "альбом": "album",
    "сериал": "series",
    "пространство": "space",
    "концерт": "concert",
    "эссе": "essay",
    "заметки": "notes",
    "читка": "reading",
    "лекция": "lecture",
    "балет": "ballet",
}

TEXTS_EN = [
  {
    "slug": "dolzhno-byt-eto-rai",
    "title": "Cultural Studies of Europe on Behalf of the Glorious People of Palestine, or It Must Be Heaven",
    "kicker": "Elia Suleiman made a film in which the protagonist influences almost nothing — which is exactly why the viewer is left alone with their own conclusions.",
    "paragraphs": [
      "Are you sure you absolutely need to know everything about the hero and the full backstory of everyone else in this film?",
      "So: you want to watch life and feel everything the characters feel. You don't watch just for the sake of it — otherwise, why bother.",
      "The standard mode of perception simply won't work on Elia Suleiman's new film, It Must Be Heaven. Characters come and go. Their fates are largely unknown and have nothing to do with the main character.",
      "The question arises: is he even a hero? What lesson is he supposed to learn to become better — and why shouldn't the viewer be the one to draw that conclusion instead? That's when casting the hero as an observer starts to make sense.",
      "He is, by the way, a man, Palestinian, fairly advanced in years — and he arrives in France. Circumstances arrange themselves so that seemingly ordinary but strange events keep happening in front of him.",
      "He barely influences any of it, and the events simply happen on their own. Perhaps sometimes he should intervene and say something — but should he? That would set off a whole chain of entirely predictable processes, and then he'd have to act according to some already-plotted character arc.",
      "So it's easier just to watch: everything around you can spin 540 degrees — you just look and react.",
      "And what if you remove the reaction entirely? The events that happen are enough on their own — completely independent, yet somehow rehearsed. Even the birds fly on cue here and, if needed, can keep you excellent company.",
      "Here you are reading this text, and it could just as easily be about some important problem. Are you ready to react to it, or is a simple statement of fact enough?",
      "Inaction in art is very illusory. Most often what you take for absence is, in fact, a well-made argument.",
      "What that argument is — that's up to you. The film's space is only a quarter full; you remain the director of this life, deciding for yourself which fragments to assemble and where to cut, filling in the rest of the story.",
    ],
    "meta": "The film It Must Be Heaven (Elia Suleiman) was released in Russia on the Beat Film Festival platform.",
    "link_label": "watch on Beat Film Festival",
  },
  {
    "slug": "dvoe-na-kachelyah",
    "title": "Two on a Swing. Where Am I in This, and Am I Even Needed",
    "kicker": "A review written not to recommend, but to process what was seen — fresh off the premiere at the Lensoviet Theatre.",
    "paragraphs": [
      "Let's agree on this: you'll read it and won't draw any conclusions. I'm quite bad at recommending you go see this show. Even now I'm writing only in an attempt to process and understand, not to tell or share.",
      "Please accept this and don't judge too harshly. In our metamodern reality it's strangely awkward to say 'I liked it' — the criteria for that have been killed, trampled, and are interpreted however suits the moment.",
      "So I want to describe my feelings from start to finish — roughly the way the show's director did herself. Whether you stay and keep reading is your call. For what it's worth, if I weren't personally invested, I'd have given up almost immediately.",
      "Let's start with the fact that I missed it. Premiere or just a regular show — either way I start worrying in advance about people who are already mine, but in fact are strangers. The question is how much closeness comes from hours spent in one room trying to understand one thing, only to end up somewhere so different it's almost insulting.",
      "And the strangest part — you can feel the energy in the audience, and at the same time it's the nicest thing: if we knew nothing about each other on some other level, our gathering here would mean nothing at all.",
      "True, you could lock yourself at home and watch it all over Zoom or on social media — but that's still a different reality, unlike the one you feel in the moment of being present.",
      "Everyone has their flaws. Maybe because I hadn't read the play's text beforehand, my boundaries dissolved and I gave myself fully to the director's vision. Every word said or done began, over time, to eat away at me down to the foundation.",
      "It didn't happen all at once. Like many, I even started recognizing myself and others in it — until it dawned on me that the show's author had genuinely dug in and, through plain storytelling, decided to crush completely. And here I remember our agreement again — or rather, my right not to hand you the correct or necessary conclusions.",
      "Because I don't know whether you need to watch it, where you stand in this text, or whether the text is even worth what you'd have to give of yourself for it. But at first I even liked it — though gradually I had to start hiding a scream that used to just be ordinary laughter.",
      "That's where the pain, confusion, and not knowing what to do with any of it set in. You've fully heard about all this before, but it's unclear where the great playwright is who will finally sit everyone down with a therapist.",
      "All your unresolved business will be worked through and settled, you'll become so happy that, of course, under no circumstances can this be true — so why not buy that happy orchestra-seat ticket then? I don't want the show to be a product you can simply purchase. The whole problem is that my position is too shaky, because the world is different. And it's far from always clear to me whether I'm the victim or the outright villain.",
    ],
    "meta": "Two on a Swing was staged in 2021 at the Lensoviet Theatre, directed by Evgenia Boginskaya. The premiere took place on April 1, 2021; this review was written after the April 21 performance.",
    "link_label": "tickets and repertoire at the Lensoviet Theatre",
  },
  {
    "slug": "robot-kostya",
    "title": "In Search of Inspiration, or How to Live Among Robots and Not Lose Your Mind",
    "kicker": "On the birth of Robot Kostya — Russia's first robotic theatre production, where Chekhovian passions turned out to be within a robot's reach too.",
    "paragraphs": [
      "Not everyone gets to become the subject of art. And yet it all depends so much on circumstance that, in the right light, anyone can.",
      "That, in part, is what creativity is — creating contexts that move people and inviting them to contemplate.",
      "There's no point explaining that theatre has long branched off in every direction, so it probably won't surprise you that Chekhovian passions are within a robot's reach too. Writing this, I realize how endlessly stingy and superficial all definitions are.",
      "Of course, robots can do anything, and soon they might replace us too. That's something I wanted to understand a little for myself — and so I ended up in a project I doubted and was afraid to be part of.",
      "For now, feeling is still what sets us apart, and 'bringing a robot to life' is no easy task. Giving it character and quirks of behaviour is possible only by searching for new forms, new meanings.",
      "I got lucky: the people around me were charged people. Besides being professionals, everyone was genuinely fired up and understood we needed this.",
      "One could easily have thrown up their hands, and then everything would have been lost and missed. Everyone has their shortcomings and strengths, but somehow it all got poured in — and a show came out.",
      "As far as I can tell, it's even a wonderful one. From the inside, every image really performed, and when the audience arrived, I felt a little envious both of the people watching and of myself, for being part of it.",
      "It's all in the details, and I don't fully understand how what happened to us, to our team, even came about. All our eyes merged into the eyes of the Robot.",
      "His name, incidentally, is Kostya — Kostya Treplev. The story is a familiar one: he loves Nina, she rejects him in every way for something insubstantial. A strong feeling up against great coldness.",
      "The rest of us, too, are endlessly writing for the drawer, and it's unclear which of us is Trigorin and which is doomed to be forgotten without glory.",
      "Do I need to explain that we moved somewhere, tried to understand something, and this show unquestionably made us different. It's not certain the robots fully understood us, or that we fully understood these strange but somehow close 'non-human agents.'",
      "So the story goes on, but it all goes in circles. All that's left is to place the emphasis correctly.",
    ],
    "meta": "Robot Kostya was created as part of the Tochka Dostupa summer arts festival with support from Planetarium No. 1. Performances took place July 15–16 at the Lumière Hall in St. Petersburg.",
    "link_label": "Robot Kostya's account",
  },
  {
    "slug": "vysokoe-razreshenie",
    "title": "Vera Polozkova — High Resolution",
    "kicker": "Poems that keep finding more and more breath in the music with every listen — and become more interesting to hear than most songs.",
    "paragraphs": [
      "It's still unsettling that in this new reality you're a dead man in most people's eyes simply because a thermometer at the entrance shows an inconvenient reading. And sometimes you think that's really all there is, that there's no saving anyone — you're walled up in this little world regardless. And you still have to somehow live in it.",
      "A lot helps, but Vera Polozkova's new album helps especially. It even feels strange to call it an album. These are poems that, with each listen, find more and more breath in the music, and listening to them becomes more interesting than most songs.",
      "Some explaining is probably in order. Thankfully we have no shortage of poets, and Vera Polozkova is a bright, well-known example. If you somehow haven't heard of her: she already has three collections out, and, I hope, more to come. She tours actively and performs in St. Petersburg every year.",
      "Her energy is so mesmerizing that it's better to fall for Polozkova live, at a concert — though this album works too. Complex, yet too simple. Understandable, yet in need of unpacking. Emotionally unsettling, yet thought-provoking.",
      "It feels strange to say everyone should listen to it. Say, I can't do without it, while others will find it needless pretension.",
      "No one will be entirely right or shamelessly wrong — it'll find the listeners it needs on its own. It helps you get through and understand everything without needing the words spelled out. What matters is the breathing — in sync, I hope.",
    ],
    "meta": "Vera Polozkova's album High Resolution was released on all digital platforms on October 2, 2020 — the poet's first full-length record in five years. The collection features 7 poems set to music by Eduard Konovalov.",
    "link_label": None,
  },
  {
    "slug": "hod-korolevy",
    "title": "How Not to Lose Your Mind in This World, and the Queen's Move — By the Rules and Without",
    "kicker": "The Queen's Gambit made chess accessible even to those who'd picked up a queen piece maybe twice in their life.",
    "paragraphs": [
      "An invisible cloud forms above certain works of art. It opens up always unexpectedly, and far from at every convenient moment.",
      "You can try to predict it, but not even the most learned specialist can guarantee it. Art is eternal, but everyone's code for unlocking it is different.",
      "The odds of making chess interesting to everyone are slim, but the creators of The Queen's Gambit managed to make it accessible even to someone like me, who'd held a queen piece maybe twice in his life.",
      "We're told, in a supposedly documentary tone, about the most talented chess player in the world. Where the truth ends and fiction begins is for you to sort out. The script is reportedly based on the life of the prodigy Bobby Fischer, but the gender swap turns the whole thing on its head, and by this point the facts hardly matter.",
      "And what difference does it make whether it happened or not. What won me over first was the sheer nerve and aesthetics — and, at the same time, the warmth and harmony — this cocktail is mixed with. Sadly, I'd already cracked the 'trick' of where it was heading by the halfway point.",
      "But that didn't make the series any less gripping, or the experience any less significant. It all came together in a way that finally convinced me: I cannot live without art. It feeds me, and without it I simply suffocate.",
    ],
    "meta": "The series The Queen's Gambit premiered on Netflix on October 23, 2019.",
    "link_label": None,
  },
  {
    "slug": "dom-radio",
    "title": "Beauty Is in the Eye of the Beholder, or Dom Radio — Irrational and Majestic",
    "kicker": "With Teodor Currentzis's arrival, Dom Radio became the city's absolute centre. A text about a space you visit in order to change.",
    "paragraphs": [
      "There was a time when the centre of gravity was Yuri Butusov's direction at the Lensoviet Theatre; now, with Teodor Currentzis's arrival in our city, that absolute has become Dom Radio.",
      "Whatever my purpose there, I always leave it full. Or rather: I go there to enter another world and come out changed. It's not for nothing they say theatre begins with the coat check — here, everything begins with the door.",
      "You really have to think hard about whether it's worth going in at all. It's entirely possible you'll fall down a rabbit hole, or simply get lost.",
      "You absolutely have to switch off from your worries and leave every means of contact with this world downstairs — a stray bit of noise can wreck the entire journey.",
      "After that you're on your own: will you find the right route, does one even exist, or can you simply relax and let yourself fly.",
      "From the outside it looks a bit like a cult — all it's missing is the stench and the curses. But it doesn't need those: my ritual happens on some other, inaccessible level, and not everyone is able to detect it.",
      "Once you've discovered the previously unknown, you rarely want to go back. It's strange when what was here felt close and dear — while outside, it's already a wake for a fairground that just closed down. And not many of its 'wonders' can compare with the confiding, twilit atmosphere of Dom Radio.",
    ],
    "meta": "This text was written after several visits to the Workshop for the Contemporary Viewer — a residency at Dom Radio, organized by conductor Teodor Currentzis's team.",
    "link_label": "musicAeterna listings",
  },
  {
    "slug": "kurentzis-znal-videl-chuvstvoval",
    "title": "Currentzis. Knew, Saw, Felt",
    "kicker": "Debussy, Ravel, Stravinsky, and Erik Satie in one evening at the St. Petersburg Philharmonic — and a hall reborn along with the music.",
    "paragraphs": [
      "Where were you, what did you feel? No, that question is entirely inappropriate for any Currentzis concert. It couldn't really have happened, and yet it did — beyond the reach of consciousness.",
      "Waking up the next morning, I realized: everything that happened at the Philharmonic yesterday was real, and it's working on me even harder now than it did then.",
      "Teo created a field, a space, and we plunged into it headfirst. Reborn, we made room for new feelings and new meanings.",
      "Quite often you want to find something bad, something out of tune — I found nothing of the sort in his music. Quite the opposite: my sense of harmony, which began with light Debussy, wasn't broken once along the whole way.",
      "Maybe I was blinded by the purity and light, but Ravel too went by tender and precise. Then came the ice, and Stravinsky struck — clearly well cared for and performed many times before.",
      "The cherry on top, oddly enough, was the audience — it had been far too long since I'd seen them in a state like that. And I was glad to see them again.",
      "Yes, we're not acquainted, and probably never will be. But together we lived through and felt a great deal. Each of us carried off something of our own, undoubtedly beautiful and bright — as delicate as the Erik Satie that played as the encore in the hall on Italyanskaya Street.",
      "And I'm certain: it will sound again, whenever we gather next. Will that turn out to be true?",
    ],
    "meta": "Teodor Currentzis and the musicAeterna orchestra performed on March 1, 2021, in the Great Hall of the St. Petersburg Philharmonic. The program included Debussy, Ravel, Stravinsky, and Erik Satie.",
    "link_label": "listings for upcoming concerts",
  },
  {
    "slug": "annette",
    "title": "The One Watching From the Abyss, or Annette — a Serious Conversation That Happened at the Right Time",
    "kicker": "A Leos Carax film in which the ending of the story isn't its limit — everyone sets that limit for themselves.",
    "paragraphs": [
      "It was long overdue, but this film needed time.",
      "It wouldn't be hard to build a moralizing text about how the hero brought it on himself — but wouldn't the very nature of it push back: you're no innocent either, and the story isn't nearly as simple as it looks at first glance.",
      "You need to decide for yourself whether you're willing to be complicit in this. If not — leave the theatre at the director's first words, because after that point what happens genuinely stops depending on you.",
      "You can feel all you want that Adam Driver's character's life is falling apart under him, but trying to come out clean from comparatively dirty water yourself is invariably pointless.",
      "You're already in the theatre, and what's performance and what's life is something you'll only figure out later, because Annette dissolves into everyone and everything, and the film's ending is not her limit.",
      "Everyone sets their own limit. The time will come, but there's no way to stop it or even notice it — same as the circumstances that landed you at the point with no roads leading out.",
      "As always, no one's going to answer the question of 'who's to blame and what to do' — and it would honestly be strange for Leos Carax to have made it any other way. Everything is spelled out, and yet every time it turns out to be far less clear-cut than it seems.",
    ],
    "meta": "Leos Carax's film Annette was released in Russian theatres on August 12, 2021. As of publication, it's available on streaming platforms.",
    "link_label": None,
  },
  {
    "slug": "maya-plisetskaya",
    "title": "A Strength You Envy and Bow to — Maya Plisetskaya",
    "kicker": "The moment when the problem of ageism stops mattering: she's 50, and she's timeless.",
    "paragraphs": [
      "Naturally, I'm still too foolish and unschooled to write about her properly. Here Maya is 50 — and this is exactly the moment when ageism stops being relevant: she's timeless, everything is within her power.",
      "The very first movement bends the atmosphere and makes life not what it was before. No question, sometimes you want art to change life so badly.",
      "All that's left is to believe we're not entirely useless here — that we're capable of making the world at least a little different.",
    ],
    "meta": None, "link_label": None,
  },
  {
    "slug": "gerda",
    "title": "Gerda, or a Breath of Air That Will Freeze Mid-Flight — But Will It Land?",
    "kicker": "A film by Natalia Kudryashova — told in verse, about a city crushed by snow, and about whether you're ready to take off.",
    "paragraphs": [
      "Snow-white flakes crush her city, and it seems no icy heart could ever thaw this moss-grown swamp.",
      "This film can only be talked about in verse. Fear, hatred in it — all of it has vanished, or sunk into a great haze. The space exists now purely out of habit. In order to live.",
      "Feeling anything at all is too painful, and gets condemned by everyone in advance anyway. Who you are in this world, and where that path out of the enchanted forest even is — not entirely clear. Striving also seems strange somehow: all that's left is an obsessive urge for total exposure before the disharmony of the outside world.",
      "The question posed — does it even need an answer, and how far must that answer go to satisfy everything you put into it? All of us struggle in the attempt — few manage to find it.",
      "But how ready are you to take off?",
    ],
    "meta": "This text was written after Natalia Kudryashova's film Gerda — in theatres from October 14, available on streaming services.",
    "link_label": None,
  },
  {
    "slug": "medeya",
    "title": "You Feel Sorry for Everyone in General, No One in Particular, or Medea — For Us, About Us, Against Us?",
    "kicker": "A film by Alexander Zeldovich, where words don't compete with the music — and the only question left is: do you understand me?",
    "paragraphs": [
      "This film is sparing with words, but the words in it don't carry their usual price or meaning — they sound, but stay ambiguous.",
      "They don't need to compete with the music: everything simply gets bandaged into concrete, the remains scatter into dust, finding a life of their own in one giant sandbox.",
      "All the music there moves as an equal, and it doesn't matter where you point it. In the end, only one question remains — do you understand me?",
      "The answers here won't keep you waiting, that much is clear — and then what were the questions even for.",
      "In that case you might as well not have started at all — since it was already known in advance. But there's one thing we don't know: is it, though?",
      "All that's left is to keep asking, endlessly and nervously, or to scream, hopelessly and pointlessly. For how long?",
      "While the clock keeps ticking.",
    ],
    "meta": "This text was written after watching Alexander Zeldovich's film Medea, available on Kinopoisk HD by subscription.",
    "link_label": "Kinopoisk HD",
  },
  {
    "slug": "intervyu-v",
    "title": "Interview V, or You Don't Choose Your Times — You Live in Them",
    "kicker": "Vertinsky in the flesh on the '7th Tier' stage of the Alexandrinsky Theatre — and the question of just how defenseless and confined a person is by their own body.",
    "paragraphs": [
      "He slowly puts on his stockings, and nothing must stop him from finishing.",
      "In Roman Kaganovich's show Interview V, the maestro Vertinsky is presented in the flesh — literally and figuratively. The space in which it all happens is so small, and it's easy to feel the fiction of it all — you just need to hold up the right lens.",
      "But it's strange not to believe: a properly measured dose of cocaine will do its job — the only question is how much strength you have to resist.",
      "Though here the audience acts more like a heavenly judge, since even the show itself is performed on the '7th Tier' of the Alexandrinsky Theatre.",
      "Camera flashes click methodically and dispassionately, helping to capture and bring things closer. Strange, but lately it's become especially clear how defenseless and confined a person is by their own body.",
      "He's afraid of getting lost, and despite an inner strength and a certain cynicism in relationships — this Vertinsky is intelligent but inconsolable. He asked not to be pitied, yet was clearly unhappy.",
      "And, judging by everything, he passionately longed for a home, a homeland, to which he was ready to be faithful spiritually and physically — who knows, Chekhov's sisters were probably in for no less a disappointment in their own ghostly Moscow. But it's worth living — which means it's worth wanting things.",
    ],
    "meta": "Interview V is a production by Roman Kaganovich and Theatre Nenormativnoy Plastiki. The role of Vertinsky is performed by Sergei Azeev. The performance took place as part of the '7th Tier' festival on the Historic Stage of the Alexandrinsky Theatre.",
    "link_label": None,
  },
  {
    "slug": "net-nuzhdy-pisat",
    "title": "No Need to Write",
    "kicker": "On how art doesn't always save you — and an attempt to simply 'keep living.'",
    "paragraphs": [
      "I always thought art saves you. But lately it turns out there's a lot to rethink in order to accept everything that's come crashing down on us.",
      "It's still hard to shift your own discourse, to put your mental health back in order — and to describe even a little without stepping into the context of what's going on, which has gone completely mad.",
      "'A little sad it all ended so fast. Actually, no, not quite…'",
      "Summing things up feels cheap, predictable, and more than a little theatrical, so I'd rather just draw, like Pirosmani. Let it be a beautiful legend, one you'd be embarrassed to tell.",
      "Because there's simply no strength or desire left to heal the broken bone, and to sit in judgment of it is painful and stingy.",
      "I set aside the search for deeper meaning and just try to 'keep living,' even though purity has long been wounded and out of reach — same as wherever it is you want to be, or want to seem to be.",
    ],
    "meta": None, "link_label": None,
  },
  {
    "slug": "dnevnik-kinozala-liminalnye-prostranstva",
    "title": "Cinema Diary: Liminal Spaces and a Festival Sprint",
    "kicker": "Six short impressions in a row — from Hoppers to backrooms: what grabbed me, and why the trend for liminal spaces is so good precisely because the puzzle never quite gets solved.",
    "paragraphs": [
      "Hoppers — a kind, gentle story about the importance of nature. Nothing beyond that, but if you just want to relax, it works.",
      "The Bride! — a classic Frankenstein story with a superb Jessie Buckley, a decent Christian Bale, and a gorgeous score by Hildur Guðnadóttir. It went almost unnoticed over here — entirely undeservedly, it's a good film.",
      "One Battle After Another — a landmark film from Paul Thomas Anderson, a contender to stay in the history books; we'll see. To me the construction felt a bit heavy-handed, closer in spirit to There Will Be Blood than to his lighter work like Phantom Thread. Too many male characters crowding one screen.",
      "The Platform — finally watched it on the recommendation of reviews of the previous films. Another liminal space — if you don't know what that is, look it up. A finely and tightly built story about survival: a platform loaded with food descends from the first level to, roughly, the three-hundredth, and the entire plot grows out of that one device. Worth watching.",
      "Exit 8 — well-crafted as a genre exercise, though in places it's basically a 'have kids already' PSA, and the woman here isn't so much a character as a plot function. Overall worth a look — also a liminal-space story.",
      "Project Hail Mary — started off strong, Ryan Gosling is good, but the runtime (an hour and a half) feels needlessly long. A genuine Gosling showcase, and the attempt at an alien character mostly works, though it's a bit too humanoid. Honestly, I liked his ship more — that turned out to be genuinely performative.",
      "Backrooms — filmed by someone in their twenties (the original title reads a bit differently). Maybe there's no deep thought in it, but it's assembled very well. What I like about the whole liminal-space trend is precisely this: the mystery almost never gets fully decoded by the end — and often not at all.",
      "One more thing: I went to see Renate Reinsve from Sentimental Value — she's wonderful here too.",
    ],
    "meta": None, "link_label": "Letterboxd: The Platform",
  },
  {
    "slug": "michael",
    "title": "Michael — Impressive, but Looks Like a PSA",
    "kicker": "Watched it for free — and it's impressive, of course: a huge budget, a conflict built with real craft. But the context of all the accusations feels wiped clean.",
    "paragraphs": [
      "Watched Michael — for free, thankfully. Overall it's impressive, as expected. But it feels like watching a PSA — a very well-made one, with a huge budget, and even the central conflict is built with real craft.",
      "Sadly, the context of all those accusations against him feels wiped clean from the film — as if they'd never existed.",
    ],
    "meta": None, "link_label": None,
  },
  {
    "slug": "shurale",
    "title": "Shurale — Hope That Fell Apart",
    "kicker": "A good cast, a beautiful image — and the film still falls apart. On when it's too soon for an actress to become a director.",
    "paragraphs": [
      "Shurale really fell apart — honestly, there was some hope: a decent cast, and it was shot beautifully.",
      "Alina Nasibullina is, of course, lovely to watch — but she should have stayed in front of the camera: the director in her hasn't quite arrived yet, which is a shame, since she's a Brusnikin graduate and has been in good films.",
      "Both Roma Mikhailov and Gena Blinov gave it everything they had. Maxim Matveyev's presence in this cast is puzzling — probably there for name recognition; he's a solid actor, but I've never been especially fond of him.",
      "I have a lot of questions about the concept. It's genuinely beautiful, I'm sure the references were all there — but it never came together into a coherent picture for me, even when I tried to read it as a piece of mythology. It didn't hold up.",
      "Still, worth a look.",
    ],
    "meta": None, "link_label": None,
  },
  {
    "slug": "nash-gorodok",
    "title": "A Film With a Killer Twist, Seen at Dom Radio",
    "kicker": "The credits roll almost exactly in the middle — and that turns out to be the twist itself. About an elderly couple, flowers, and a premium version of ascension.",
    "paragraphs": [
      "I love Dom Radio for showing films you won't find anywhere else, for free. That's also the problem.",
      "This film had a genuinely great twist, and it worked purely off the audience's raw reaction. The film ends almost exactly at the midpoint — for some people, anyway. Credits roll. Fine, we're not the first to put the credits at, say, minute thirty, but here it was brilliantly justified: the 'with people' version of life had ended, and after the credits came pure Thornton Wilder — the actual Our Town. But the devil's in the details: a concept is a concept, and pulling it off is a different skill entirely.",
      "The story, essentially: an already elderly couple lives a modest life — she works at the church, he tends bar in the evenings. They seem happy with each other. And suddenly the female character decides to spend all the money her husband had been saving for their first mountain trip in forty years — on flowers. She's rewarded for it: she dies utterly happy, driving into a pond in a car full of flowers. I've simplified a bit, but that's essentially it.",
      "That's the moment the credits roll — people start leaving, and the programme's curator rushes out to explain this isn't the ending, please come back. And then a kind of pre-grave afterlife begins, complete with all the fitting comic details.",
      "A speaker announcing 'connected' just about killed me: an angel-agent comes to visit our heroine, reads out the same script given to everyone who's dying, and offers a choice — 'standard' or 'premium' ascension, exactly like real life. And this is read out over the sound of a speaker connecting — that's when the 'connected' from the start of the film paid off.",
      "An independent film, made 'for pennies,' but with an excellent sense of humour — pitch black in places — and good taste: the black comedy never slides into pure comedy, the devices keep landing, and the humour is genuinely clever here and there. It suited me completely — the impression even outdid the scent of Zielinski on my hands: I always wash them when I go to Dom Radio, that's the exact bottle they keep there, and I like the smell.",
    ],
    "meta": "This text was written after a free screening at Dom Radio.",
    "link_label": None,
  },
  {
    "slug": "krasnaya-pustynya",
    "title": "Antonioni's Red Desert — Cinema You Feel",
    "kicker": "The director's first colour film, where even the colour that was there wasn't enough — and the theme turned out to be a crisis of everything.",
    "paragraphs": [
      "Watched Antonioni's Red Desert — now this is cinema you feel you need to watch alone with yourself.",
      "Genuinely strange: Antonioni himself talks about pure admiration for these industrial giants, while what you're watching is a crisis of everything — an attempt to find yourself amid endlessly flowing oil and a poisonous fog filling the mind down to the bone and the heart.",
      "Interesting how the director tried to colour in absolutely everything, even though this was his first film in colour — and still the available colour wasn't enough, so he added more.",
      "It was a little hard to adjust to the film's unhurried rhythm — and, judging by the room, not just for me.",
    ],
    "meta": None, "link_label": None,
  },
  {
    "slug": "novyy-ozon",
    "title": "The New Ozon — Beautifully Shot, as Always",
    "kicker": "A black-and-white film in which, by the end, the hero loses his head, but not its meaning. One of the few reasons to go to Dom Radio for something like this.",
    "paragraphs": [
      "I have to admit: I'd completely forgotten the original, though reading it back then hit pretty hard. Here it's a similar effect. I can say Ozon hasn't made a film this strong in a long time — that's not to say the rest is bad, just that this one earns the claim.",
      "An unambiguous like. And of course, only I would go to Dom Radio for a black-and-white film in which the main character gets his head cut off in the end — but not its meaning.",
      "It's shot, of course, very beautifully — Ozon doesn't know how to do it any other way, forgive the cliché.",
    ],
    "meta": None, "link_label": None,
  },
  {
    "slug": "novyy-dzharmush",
    "title": "The New Jarmusch — Maybe Just Not My Film",
    "kicker": "Everything is beautifully calibrated, the moves land — but there's a sense the director has simply gotten old.",
    "paragraphs": [
      "Watched the new Jarmusch. Maybe I wasn't in the right mood — everything is beautifully calibrated, the moves land, but it feels like he's simply gotten old.",
      "Maybe it's just not my film — it's closer to the Coffee and Cigarettes side of him, and I'm not a huge fan of that side of Jarmusch. I'm closer to the one who made Paterson or Night on Earth.",
    ],
    "meta": None, "link_label": None,
  },
  {
    "slug": "gamlet-kolyada-teatr",
    "title": "Nikolai Kolyada's Hamlet — Physically Filthy Theatre on the Edge of Kitsch",
    "kicker": "A world on the verge of disappearing, turned into one big dump. Not a show for casual viewers — and almost a manifesto for the theatregoer, folded into a review.",
    "paragraphs": [
      "A world on the verge of disappearing. It's turning into one big dump, populated by monsters. And this isn't another blockbuster of the fantastical kind — this is what Nikolai Kolyada's not-so-new production of Hamlet looks like already: genuinely, physically filthy theatre, right on the edge of kitsch.",
      "I don't want to convince you to go see it — especially not right now. You need to be ready for it. This theatre isn't for casual viewers, and on top of that it demands the kind of immersion that's only possible in the room.",
      "But if you can't resist tasting this theatrical delicacy while the season is still dead — please, be my guest. Especially since they tried to make the recording with real warmth and whatever technical means were available at the time.",
      "This is where I want to make the case for theatres publishing good recordings of their shows. There's no way to exist in the digital age without that. It's understandable that the atmosphere gets cut off in the process, but not everyone can afford to travel out to, say, Yekaterinburg, and touring life is a sore subject, especially for small theatres like Kolyada-Theatre.",
      "It's become fashionable in recent years to praise provincial theatres — in this case, I want to do it with genuine pleasure. It's impressive that they're not afraid to speak freely, in their own language; I'm reminded once again that theatre is one of the most democratic of the arts.",
      "But don't expect a clean-cut yes or no from me: overall, the show left me with fairly mixed feelings. It's not that it's untalented, bad, or primitive — everyone clearly tried very hard. The sheer amount of props, references, and meanings is staggering, but personally I found it lacking in air, a bit of philosophizing, room to breathe. I'm a different kind of viewer, and no one owes it to me to accommodate that.",
      "I'm only looking for my own thing — something that leads to catharsis, that I won't forget for years, that will stay stamped in memory as something bright and vivid. Everyone can find their own: for me, personally, Erenburg's theatre is closer, where everything physical is measured and balanced with real skill.",
      "It's a good thing there's different theatre for different audiences — otherwise it would be boring in our fairly standardized world. At the same time, we're obliged to stay open, to keep looking for ways to connect, rather than sitting there passively, reacting like one of Pavlov's dogs.",
      "Kolyada, incidentally, has a ton of fans — I don't know how organized they are, but on tour they pelt the stage with flowers and bring wine by the crate.",
      "So whether to watch it or not is up to you. One thing I can say for certain: you won't have wasted your time.",
    ],
    "meta": "P.S. If anyone noticed — the attached track is from Kubrick's 2001: A Space Odyssey. It made the association, presumably, thanks to its own primal quality, which this version of Hamlet has plenty of too.",
    "link_label": None,
  },
  {
    "slug": "poklonnitsa",
    "title": "The Admirer — When a Classic of Soviet Cinema Burns Out",
    "kicker": "A serious cast, a cinematographer who shot Balabanov's films — and the film still tries to squeeze out tears with a cheaply built romance.",
    "paragraphs": [
      "I don't want films where Anton Pavlovich Chekhov gets mocked quite this shamelessly.",
      "I honestly watched Vitaly Melnikov's The Admirer all the way through — a director, incidentally, of The Elder Son. The film was made in 2012, based on the sentimental, semi-documentary memoirs of Lidia Avilova, who genuinely knew Chekhov.",
      "At first glance everything looks fine: the money is visible on screen, the cast is well chosen, and the cinematographer is Astakhov, who shot almost all of Balabanov's films.",
      "But there was a very determined effort to bring me to tears with a cheaply built romance between Chekhov and this same Avilova. For the occasion, Kornelyuk even wrote a special melodramatic musical theme.",
      "I diligently refused to believe any of it — at one point I was ready to protest right there in the Lenfilm theatre seats. Because there's no need to spend that long convincing me the film was shot in St. Petersburg by endlessly parading postcard-perfect views of the city. I got the point.",
      "And I also realized that, for some reason, I believe the far-from-realistic Beanpole, but not The Admirer, deliberately stuffed with Chekhov quotes.",
      "That's usually how it goes with aging classics of Soviet cinema: they burn out, but people keep asking them to direct anyway — or, probably, they still want to, out of habit.",
      "Naturally, the strongest actors of the moment agree to work with them. The Admirer's cast is serious — Oleg Tabakov, Kirill Pirogov, Svetlana Kryuchkova, and that's just the leads. Everyone else is decorated too — but their characters are flat, dull, and cartoonish.",
      "If the wonderful Oleg Andreyev plays a jealous husband, then that's all he remains — just a jealous husband, no drama, no Chekhovian torment. That said, Sergei Barkovsky's sketch is genuinely excellent — the moustached owner of a crumbling literary newspaper: perfect in lighting, in makeup, in setting.",
      "Everything else here is a heavy, costumed construction that milks the government budget for all it's worth.",
    ],
    "meta": "The film The Admirer (dir. Vitaly Melnikov, 2012).",
    "link_label": None,
  },
  {
    "slug": "nebesnyy-taper",
    "title": "The Heavenly Piano Player — a Documentary Love Letter to Karavaichuk",
    "kicker": "A brilliant Soviet pianist and composer whom the Ministry of Culture is in no hurry to show the world, even though it financed the film about him itself.",
    "paragraphs": [
      "I don't understand why the Ministry of Culture wants to sit on such a whole, coherent film — the very one it financed itself. Why the director has to fight just to get it shown anywhere at all.",
      "Russian Cinema Day just passed — did you see what made the programme? A real shame. I don't think the Rodina cinema is obligated to screen something as commercial as, say, Policeman from Rublyovka — maybe even a decently made one. But on exactly this kind of day it's critically important to promote independent cinema, like The Heavenly Piano Player: it's absolutely clear it will never get proper distribution, so let at least a small share of the audience learn about the brilliant Soviet pianist and composer Oleg Karavaichuk.",
      "My own history with him is short. My first, accidental encounter with his music happened at Lev Dodin's staging of The Possessed. Then came Karavaichuk's sudden death; sad as it is, that's what became the news hook for getting to know this man better. And finally I made it out to see the film, shot by people who had always been nearby, methodically documenting all his concerts and, uniquely, his rehearsals too.",
      "I really didn't expect it to move me this much — even now, remembering and re-listening, I keep tearing up. The maestro didn't like being recorded, and only trusted the people closest to him with it — maybe that's exactly why the film turned out so personal, so piercing.",
      "Maybe director Sergei Lando shouldn't have included his own voiceover — it makes the perspective a bit subjective and distracts from the direct, personal encounter with the artist. But that's a matter of taste: I'm always glad to hear Dreiden's voice, warmly telling us about a man who's no longer here but who will forever remain captured on film — our own 'city madman,' Oleg Nikolaevich Karavaichuk.",
    ],
    "meta": "P.S. The filmmakers said in the discussion afterward that they're hoping to show The Heavenly Piano Player at Novaya Gollandiya next — worth keeping an eye out.",
    "link_label": None,
  },
  {
    "slug": "vernost",
    "title": "Nigina Sayfullaeva's Fidelity — More Bad Than Good",
    "kicker": "A cast willing to do anything for the sake of art — but the film drowns in a pretense of meaning that, it seems, was never really there.",
    "paragraphs": [
      "A shame. The screening ends, and during the credits you're already jotting down the film's flaws and moving on with your day — there won't always be some visiting German-theatre miracle shaking you to the bone and leaving an impression for life rather than just for the time it takes to write about it. Time to get used to it: there are good films and bad films.",
      "Nigina Sayfullaeva's Fidelity is more of a bad film than a good one. My bright, naive expectations were not met at all: what came out felt more like a fight against our society's eternally forbidden topic of sex, as if the nineties never ended and we'd suddenly been given permission to shoot everything explicit — and out it all poured.",
      "I genuinely don't understand what Anton Dolin, who worships Lars von Trier to the point of exhaustion, found revolutionary in this film. With von Trier, sex was justified one hundred percent; in Fidelity it's presented simply as a fact: here, look, be happy, we've been given permission.",
      "Why must some dim-witted authority always stand over us deciding what we're allowed to do? Why do we have to bleep out swear words in cinemas? Why is it assumed the audience will be corrupted by seeing two people having sex?",
      "Thankfully the cast is mostly made up of unguarded people who aren't afraid of explicit scenes and are willing to do anything for the sake of art. Zhenya Gromova is now the sole reason I went to the cinema at all: a soft, unstrained, very personal performance — you can see she inhabits every moment, working carefully not to overdo it while still making the character memorable. Alexei Agranovich is simply a titan.",
      "All their effort gets undone by an endless pretense of meaning and subtext that, it seems, simply doesn't exist. Sometimes it feels like the actors aren't saying their own lines — either it wasn't rehearsed, or the roles were never properly worked through.",
      "It could have been a fresh, young, uncompromising piece of work, made without a care for public opinion. It's genuinely a shame, honestly.",
    ],
    "meta": None, "link_label": None,
  },
  {
    "slug": "irlandets",
    "title": "The Irishman — Three and a Half Hours of a Classic People Will Rewatch",
    "kicker": "Scorsese, a de-aged De Niro and Pacino, 309 scenes across 170 locations — and a hero who simply drifts along, because he no longer needs a soul.",
    "paragraphs": [
      "Tired of endless sequels, prequels, and other minor nonsense, I finally got to Martin Scorsese's The Irishman. The script is based on Charles Brandt's book I Heard You Paint Houses, in which Frank 'the Irishman' Sheeran confesses to the murders he committed.",
      "The film didn't get a theatrical release — you probably know it was kept out of cinemas over a dispute with Netflix: the two sides couldn't agree on putting the film online after a theatrical run, the way it's usually done. Good that it came out at all, even like this. They poured in an enormous budget, de-aged Al Pacino and De Niro, shot 309 scenes across 170 locations — and in the first half hour, that scale alone makes your head spin.",
      "The film itself pulls you in instantly, like an easy card game. I missed the moment when you'd usually forgive the director all his sins, chalking it up to budget and fatigue, and just keep watching, trying not to ruin your own mood. But my sneaky plan was foiled by a perfectly constructed piece of work in which you genuinely can't find a flaw — though, admittedly, I wasn't looking for one.",
      "Let me stop here and try to calmly describe what I saw over three and a half hours. That's quite a long runtime for a film, by the way — practically a whole lifetime, in which we make hundreds of choices and constantly doubt them, with no way back. And that's exactly how it goes here: no sooner has De Niro's Frank Sheeran gotten a taste of working for the mob than it's already sucked him into its den, not letting go for a second. One step left, one step right — you're shot.",
      "The hero doesn't even think of resisting — he simply drifts along, no days off, no lunch breaks. He's so deep in it that he no longer needs a soul to make decisions in anyone's favour: a simple set of actions is enough, with no room for attachment, love, or friendship.",
      "The world cracks when Jimmy Hoffa, played by Al Pacino, appears — but it only cracks: he's not fated to survive the bullet already fired at him.",
      "I won't waste your time with empty raving — I'll just say we're watching a classic get released, one people will keep coming back to. And we'll keep being handed the same grim diagnosis — will it ever change?",
    ],
    "meta": "The Irishman (dir. Martin Scorsese, 2019), script based on the book by Charles Brandt.",
    "link_label": None,
  },
  {
    "slug": "opasnaya-zhalost-blizkie-lyudi",
    "title": "Beware of Pity and Close Ones — When a Director Takes Control of the Text, and When Not",
    "kicker": "McBurney handled Zweig's novel without fully cracking how it's done. Bondar didn't handle Vodolazkin's prose — or the space of the small stage.",
    "paragraphs": [
      "Sometimes you want to ask certain directors not to take on serious literary texts — more often than not, they don't pull it off: they get buried under the weight of metaphors and comparisons. You have to aim not to retell a story you loved, but to create your own, personal one. Never mind that the author won't like it — authors rarely like much of anything anyway.",
      "In the show Beware of Pity, Simon McBurney managed to take real control of Stefan Zweig's masterful novel. The dynamics of the action held together, and you could feel the director speaking about his own wounds and struggles. But I still couldn't quite trace the construction — understand how it was built.",
      "In the new show Close Ones on the Youth Theatre's small stage, on the other hand, everything is clear. Almost too clear — which is exactly why it's boring. The young director Elizaveta Bondar was struck by Evgeny Vodolazkin's prose and wanted to make a show out of it. What came out felt sort of contemporary, sort of fashionable, with a sort of space transformation thrown in.",
      "At the start we were shut into a room with transparent windows, behind which the entire action took place; the audience sat on swivel chairs, free to spin around while waiting for the actors to move. And the actors kept moving, endlessly, for some reason — presumably to keep things lively.",
      "In the process of all this movement the director seemed to entirely forget it needs to be justified, at least somewhat worked out. Apparently assuming the audience wouldn't notice the blind spots, the actors kept switching up the rhythm of their movement in ways clearly not built for this stage. Having taken on the genuinely huge space of the small stage, Bondar didn't manage it either — she just had everyone running back and forth for no reason.",
      "In bad shows you start mentally attaching other solutions to them right away. Here almost nothing worked for me. There was one good moment — with a repeated phrase — but even that got smothered under an endless stream of text in the end.",
      "As they used to say at the coat check: the form choked the content. I'm afraid there wasn't even any form here — it was tacked on purely for the creators' own enjoyment. It would have been far more interesting done as a staged reading — something I often advise myself, and you as well: if something can be cut, it's usually better cut.",
    ],
    "meta": "P.S. The photo is from Simon McBurney's Beware of Pity.",
    "link_label": None,
  },
  {
    "slug": "gadkie-lebedi",
    "title": "The New Lopushansky — Almost a Straight Adaptation of A Gentle Creature",
    "kicker": "Expected another round of Russian misery-porn, got a literary, religious story worthy of Dostoevsky. Maxim Sukhanov delivers the best performance in Russian cinema this year.",
    "paragraphs": [
      "It's a genuine joy when a film doesn't just meet expectations but exceeds them. That's what happened with Konstantin Lopushansky's new film — I've followed his work for a long time, met him in person once: a difficult man, but a wonderful artist.",
      "From the trailer it looked like another round of Russian misery-porn — I've had my fill of that, don't want any more. To my surprise, what came out was an entirely literary, religious story worthy of Dostoevsky's novels. Seriously — read the plot summary: it's almost a straight adaptation of A Gentle Creature.",
      "A blind girl (Vasilisa Denisova), an absolute angel, marries a wealthy tyrant (Maxim Sukhanov) so he'll pay for her eye surgery. Her sight returns right at the start of the film. From there, it's nothing but torment, horror, and the sheer nastiness of our corrupt reality.",
      "In most other Russian cinema everything follows a predictable pattern. Here, despite fairly crude camerawork, there's some ineffable pull — whether it's the achingly beautiful shots or the black humour helping you survive all the horror.",
      "Maxim Sukhanov gives the best performance in Russian cinema in at least the past year. He manages to embody everything vile and terrifying, leaving no hope for a happy ending. His facial expressiveness works equally well for the cultured intellectual of Lopushansky's previous film and for this film's blunt, forehead-first merchant.",
      "The story's uniqueness lies in its being entirely timeless; that might also be its flaw, since the director seems to have forcibly stripped it of any markers of the present day. But to me the locations felt oddly close to home — I even recognized a couple of them.",
      "The second, and central, role belongs to newcomer Vasilisa Denisova. Some will probably criticize her, but for me she handled every demand of the part; she happens to act with us, at the Socio-Artistic Theatre. Lopushansky always has good luck with casting — for instance, in The Ugly Swans, a very young Laura Pitskhelauri delivered her first substantial film role.",
      "Everything else — the symbols, the colours, the light — is thought through and rhythmically composed; the aftertaste of a strong film stayed with me the whole day after the screening. Lovely, but cruel: be prepared for violence on screen and around it. Then again, it all depends on how much this world has already worn down your soul.",
    ],
    "meta": None, "link_label": None,
  },
  {
    "slug": "myunhgauzen-brachnaya-istoriya",
    "title": "The Very Same Munchausen and Marriage Story — On How Nobody Wants to Listen to Anyone Else",
    "kicker": "The problem of tolerance sits at the top of all our problems. Zakharov was already shouting about it under Soviet censorship — now it only rings louder.",
    "paragraphs": [
      "What kind of world and order can we have if even people close to each other often can't agree on anything. In our country the problem of tolerance and differing opinions sits above every other possible problem — no one wants to hear a different point of view, the official one, the only one, is enough for everyone: it's calmer, safer that way.",
      "And yet every year they still play Mark Zakharov's The Very Same Munchausen on TV, a film that shouts, quite clearly and loudly, about the importance of listening to one another and accepting a person as they are. Sure, it was made under pressure from Soviet censorship — but it only grows more relevant now.",
      "The level of aggression seems to be rising everywhere, not just here. It's no accident we got Marriage Story, where a seemingly successful married couple (Adam Driver and Scarlett Johansson) hits a massive crisis that leads to divorce.",
      "In the comments people started attacking the fact that the main character's father turned out to be gay and left the family — a strange complaint: it's mentioned exactly once, entirely in passing, with no follow-up. Apparently that's just our national trait, hammered into our heads in advance — fighting against same-sex relationships.",
      "It was only after Baron Munchausen's death that people understood the value of his life; in Marriage Story that realization also arrives closer to the end, but with a far heavier weight for the viewer to shed as well — otherwise nothing quite falls into place.",
    ],
    "meta": None, "link_label": None,
  },
  {
    "slug": "lyubov-noe",
    "title": "Gaspar Noé's Love — Art Arrives on Time, or It Doesn't Arrive at All",
    "kicker": "Armchair critics called it porn for intellectuals, and it was banned from release here. On what happens when you end up in the wrong world — or the wrong time.",
    "paragraphs": [
      "The director worked on me a little too well — the night after watching it, it's not just his images that show up in my dreams; a different film starts playing too.",
      "Armchair critics declared Love pointless porn accessible only to intellectuals, and, of course, it was banned from theatrical release in our country. I'm not one of the lucky ones who saw it in a cinema, though five years ago there might not have been room for it either.",
      "Works of art need to arrive at the right time. If you feel you haven't grown into one yet, don't even bother torturing yourself over it — it's pointless. Sometimes you've simply ended up in the wrong world: trying to force your way into understanding it is more likely to fail, and could even ruin the experience for someone else you know.",
      "So be careful choosing what you're about to watch, come to it with an open, free mind — connecting is entirely on you, no one else can do it in your place. The viewer's mission is priceless: you have to accept, to realize this is for you. If it isn't working, set it aside for a while — maybe in a few years the film will open up in richer colours.",
      "Many works of art only get understood by later generations, not by their author's contemporaries. It's painful to admit, but artists are sometimes simply born too early — more often, we ourselves just aren't ready to reorient toward a vision that was previously inaccessible to us.",
      "Ideas about reality itself are relative, everyone has their own version of it. Just as letters carry their own shade of meaning, colours too are read completely differently by our brains — every light-tone is processed psychologically with its own particular emotion: if a colour grates on you, it can be used as aggression; a warm one, as calm and harmony. Dots and commas placed in unexpected spots can stir you up and switch on the imagination — the same way a strobe light pulls you back out of your own head and into your own emotions and experience.",
      "Directors use this actively, weaving these devices into their films. Gaspar Noé made Love — a film that itself resembles a dream, or, more precisely, a drug-induced haze. Submit to it, and you'll get the maximum possible amount of both pleasure and pain.",
    ],
    "meta": None, "link_label": None,
  },
  {
    "slug": "eyforiya",
    "title": "Euphoria — a Show About Drugs That's Really About Not Being Understood",
    "kicker": "A portrait of the modern person who prefers electronic communication to real contact — and the price paid for it.",
    "paragraphs": [
      "We all live on compromises — you have to accept what you don't like, because there will always be someone else ready to blow the whole thing to pieces. On one hand, jolts like that are necessary, or else you'd freeze inside your own invented world; on the other, recovering from them, getting back to yourself, is hard. It hurts to realize a person doesn't understand you and likely won't anytime soon.",
      "But you have to strive for dialogue, urgently — otherwise we'll all turn into a community of scattered squares: sort of fitting together, but forever running into each other's blunt corners.",
      "It seems contemporary series culture understands this and is starting to talk about the sharpest issues of our time. If you don't look too deep, you might think Sam Levinson's Euphoria is about drugs; in fact it's about the lack of understanding between people who are close to each other. Something in these 'parent and child' relationships keeps them from growing and moving forward normally.",
      "And, of course, in their deeper musings, the characters keep arriving at the realization that nothing here is anywhere near perfect and that they'll have to act, not wait for help. It's exactly out of conflicts like these that teenagers' worst mistakes are born — planted in their behaviour simply because, one day, a parent couldn't find the strength to talk about the simplest things.",
      "There's the portrait of the modern person, who prefers electronic communication to the real thing. The result: fears, depression, drugs as a temporary escape from the problems, one that will still leave irreparable psychological and physical damage to the state of the soul — hardly something pills can fix. It takes real courage to deal with yourself; finding the mistakes is only step one, you still have to learn to fix them, before it's too late.",
      "I think Euphoria, like the classics, deserves to be watched by everyone — especially since it's far from boring and genuinely beautiful: the show grabs you from the very first frame, the pacing never lets you relax or drift. And that's exactly the point — we need to talk, not stay silent.",
    ],
    "meta": None, "link_label": None,
  },
  {
    "slug": "za-belym-krolikom",
    "title": "Following the White Rabbit — the Therapeutic Effect of a Second Text About One Show",
    "kicker": "Writing a second post about the same Roma Kaganovich show, because reciting the same tired phrases about a work's quality feels far too cheap.",
    "paragraphs": [
      "This is happening for the first time: I'm writing a second post about the same show. It's more of a therapeutic act — apparently I can't hold it all in, there's a real need to say it out loud. Reciting the same tired phrases about a work's quality, like a mantra, feels cheap and completely pointless; it's far more interesting to build something of my own out of it — in my case, let it be a text.",
      "I have a real soft spot for small forms: a compressed format doesn't let an artist wander much and forces a focus on what matters. Before Following the White Rabbit, when I asked about the runtime, I even said out loud that an hour-long piece sounded like it might drag. And once again I had no idea that, all the way into the next day, I'd still be gripped by an anxious, faintly hysterical feeling from what I'd seen — or, more precisely, felt. Everyone sees things differently, and maybe something simply opened up for me that I hadn't noticed before.",
      "It all starts, of course, with the atmosphere — genuinely unusual people show up at independent theatres; it's largely a deliberate choice made in favour of people who make theatre purely out of what they have to work with.",
      "I too need to periodically ask myself why theatre matters in my life. These days, I think, I come here to talk. Don't get me wrong — I'm not trying to disturb the rest of the audience; more often, unfortunately, the opposite happens: what matters to me is dialogue with the director and the actors, wanting to understand what they think about it, maybe even to argue. And a fair question follows: what's wrong with film for that purpose? Because there's no live energy there, right here, right now.",
      "A show doesn't happen unless people on both sides genuinely invest, today, specifically — it has to be done every single time. At the Theatre Nenormativnoy Plastiki show, I'd say the dialogue came together, at times even productively.",
      "It hurt and felt good at the same time, thanks to the form Roma offered up — a dynamic jumping between images, an alternation of kitsch with a fully realistic, dramatic story. The characters were introduced gradually, and when their threads finally tied together at the end, it hit twice as hard.",
      "It's nice to notice, especially with young directors, that you're essentially watching the same films, the same shows, listening to the same music — all of it finding its way into the fabric of the contemporary production. Knowing your reaction to blatant fakeness, the director deliberately steers from primitive provocation to a far higher level, holding the balance between vulgarity and substance. At first you resist it, refuse to believe the disharmony of the action — and only later understand what all that manipulation of the audience's perception was for.",
      "That's exactly the sweetness of art that deceives you a few times over — and in the end you're left looking foolish, but it's a wonderful, beautiful kind of foolish to be.",
    ],
    "meta": "Following the White Rabbit, by Roman Kaganovich and Theatre Nenormativnoy Plastiki.",
    "link_label": None,
  },
  {
    "slug": "lyubimovka-pechenkin",
    "title": "Philosophers at Lyubimovka — a Staged Reading That Never Made It to a Full Production",
    "kicker": "During the young-playwrights festival, Teatr.doc bursts with tension and joy — and the best of the readings can be watched without leaving your own city.",
    "paragraphs": [
      "During the Lyubimovka young-playwrights festival, Teatr.doc bursts at the seams with tension and joy — a huge amount happens there. I wasn't there myself, but even from the coverage you can feel that unreal atmosphere of shared creation and celebration.",
      "They send in texts, some brilliant, some less so, but it's always fascinating to dive into someone's world through them — whether the form is polished or naive. Anyone in other cities should keep an eye on the festival's YouTube channel, where all the readings, with discussions, plus lectures and masterclasses, are posted: I'm sure even a viewer with no real background in theatre will find something to like.",
      "Both for pleasure and as a professional necessity, I regularly watch staged readings — and always seem to miss the ones happening live in St. Petersburg. So from now on I'll start dropping locations and details here, so you can dive into the world of playwriting too — who knows, maybe you'll end up writing something, since the law, for now, doesn't forbid it.",
      "Today's pick might seem obvious, unremarkable, nothing new: Valery Pechenkin — you all know him from the lectures he gives before every show on the main stage at Gogol Center, where more than one of his plays has been staged too.",
      "Philosophers, as far as I know, never made it to a full production — possibly thanks to this very successful reading. Funny and tragic, uncompromising and surreal.",
    ],
    "meta": None, "link_label": None,
  },
  {
    "slug": "teodor-ioannovich-masterskaya",
    "title": "Teodor Ioannovich and the Workshop for the Contemporary Viewer",
    "kicker": "Currentzis turned Perm from a provincial backwater into a cultural centre — and was then 'exiled' back to the city of his student years, St. Petersburg.",
    "paragraphs": [
      "Sometimes, if you want something badly enough, it happens. Not always, but you have to hold on to hope: it's not that nothing ever happens — sometimes it happens even more than you wished for. And then you're happier still.",
      "Once upon a time Currentzis lived in Perm — and not just lived there, but worked on behalf of the people, trying to turn this backwater into a modern cultural centre. Others tried too, not everyone managed it — Currentzis did. He invited talent from abroad, organized events accessible to ordinary people, and the people grew better, more educated for it. Apparently that didn't sit well with someone, and the 'devil of Russian theatre' got sent off to St. Petersburg — the city of his own student years.",
      "We'll see how long our officials can hold out, and whether Teodor Ioannovich decides to wear down the minds of the St. Petersburg intelligentsia by attrition.",
      "I understand it's all much more prosaic than that: someone couldn't agree on money, someone said something unpleasant at the wrong moment — this will always stay locked up seven ways. But it's nice, sometimes, to think that art isn't made for profit, even though, more often than not, everyone needs their cut — you can't exist without money after all. And it's easy to see why Currentzis is running concerts on such a massive scale right now: Dom Radio, where he stages his experiments, has to be maintained, the rent paid, the future thought about. And it does seem like, more or less, everyone ends up better off.",
      "Completely free of charge for visitors, Currentzis's team runs the Workshop for the Contemporary Viewer — exactly the kind of care for the perceiving mind that's been sorely needed: simple things explained in plain language, enriching the cultural and intellectual level of a person who will come back to the theatre and won't be nitpicking the absence of period-accurate costumes. Of course Teodor can't keep an eye on everything, and there are occasional slip-ups.",
      "I managed to catch two lectures. The first was a genuine misfire: the lecturer on Beethoven ran the session like a university class, the kind where the teacher isn't particularly invested in getting people to love the subject. I'm speaking about the majority here — I know there are exceptions, but more often it's tired people with outdated ideas who simply got unlucky.",
      "Thankfully, the conversation with a sound producer, a practicing professional, genuinely worked — it doesn't even feel right to call it a 'lecture,' it was a conversation about everything, including, incidentally, the actual topic. He wove in his own work, imposed nothing, and just talked freely for a couple of hours — and it wasn't filler, it was measured, rational reflection backed by facts. I arrived deeply skeptical and left inspired — I think that's exactly the emotion that's supposed to arise in Currentzis's space: a place of freedom and dialogue about art.",
      "To get in, you have to give up your phone — knowledge is supposed to be alive and valuable, and the path to that knowledge runs through the half-lit floors and corridors of Dom Radio. And for a long time afterward you still can't quite recover from the jolt of knowledge you've just received.",
    ],
    "meta": "On the Dom Radio residency and Teodor Currentzis's Workshop for the Contemporary Viewer.",
    "link_label": "musicAeterna programme",
  },
  {
    "slug": "starshiy-syn",
    "title": "The Elder Son — a Show That No Longer Exists on Record",
    "kicker": "The Lensoviet Theatre never did publish a recording of Yuri Butusov's legendary production. All that's left is a video posted by kind strangers.",
    "paragraphs": [
      "Let me allow myself one moment of weakness — no film I've seen recently has moved me the way this show did. I figured the Lensoviet Theatre, which never bothers much with its own archive, would never publish a recording of Yuri Nikolayevich Butusov's The Elder Son — and, in fact, that's exactly what happened.",
      "I hope that someday, preferably in my lifetime, things get better both for the people who work there full-time and for the people who come to visit — for now there's no sign of that on even the most distant horizon. So I have to keep remembering the show through a recording posted by kind strangers.",
      "Don't think I'm mourning the fact that it's no longer in the repertoire — everything happened the way it was supposed to, and there's no changing that. Of course I'd love to bring it back — but not right now, only in bright, pleasant memories: back when Dima Lysenkov was still achingly young, playing a forty-year-old father; when Laura, my absolute love, was only just starting to conquer the stage, but you could already feel her style, her rawness, her ache.",
      "The cast is now made up of successful actors — I really want to believe they'll reunite in new work together someday, or find their own paths however they wish: no one's forcing anyone, everything has to come from the heart. Better not to lie to yourself about that — otherwise it eventually turns into a drama, and who knows whether it'll resemble a Vampilov play, or turn out to be something heavier.",
    ],
    "meta": "P.S. I honestly meant to go see La Dolce Vita that day, but it didn't work out — sorry if I ruined the first day of spring for anyone hoping to remember it differently.",
    "link_label": None,
  },
  {
    "slug": "krolik-dzhodzho",
    "title": "Jojo Rabbit — a Film About Nazism I Ended Up Loving More Than Expected",
    "kicker": "Taika Waititi plays Hitler as a ten-year-old boy's imaginary friend — and somehow lands a rare, successful fusion of form and content.",
    "paragraphs": [
      "Jinxed myself, as they say: Taika Waititi made a film I ended up loving a great deal — and it's about Nazism.",
      "Jojo Rabbit is one of those rare cases where a striking form fuses beautifully with the content. On the surface it's just another coming-of-age drama set under total control and obedience. In the first half of the film I couldn't shake the thought that Waititi had decided to make an actual textbook on how a rigid ideology gets built — after all, he plays Hitler himself, and Hitler shows up not as some terrifying master of the globe, but as the imaginary helper-friend of a ten-year-old boy named Jojo.",
      "The Führer became a cartoon figure a long time ago — it's just that, over here, apparently, no one can quite accept that: after the harmless The Death of Stalin got banned, Russian producers' self-censorship kicked in, and no one even considered releasing Jojo Rabbit in cinemas. No one over here seems tired yet of the 'Germans are the enemy, Russians liberated the whole world' formula.",
      "We've understood for a long time: if a person hating people with warts appeared, they'd immediately start exterminating everyone with warts, regardless of nationality. Every person is unique, and there's no reason to burn someone at the stake just for thinking differently — violence never leads to anything good, all you can do is talk. That's exactly the thought running through every relevant contemporary film. It's fairly predictable that Jojo manages to step past his own convictions and help the Jewish girl his house is hiding — but will you manage to genuinely understand the Other? You don't have to accept their picture of the world, you just have to keep striving to understand it.",
      "I'm deeply imperfect myself, I've got plenty of stereotypes, and I try to shed at least some of them — even in this text there's, for instance, a bit of contempt for the state machine. So just watch the film — maybe it'll get you thinking too. The main character's mother, incidentally, is played by Scarlett Johansson — in case that matters.",
    ],
    "meta": "Jojo Rabbit (dir. Taika Waititi, 2019).",
    "link_label": None,
  },
  {
    "slug": "dyadya-vanya-tuminas",
    "title": "Rimas Tuminas's Uncle Vanya — a Show That Still Works Even on Video",
    "kicker": "Ten years since the premiere, the devices already read as archaic — and the catharsis still hits, even through a screen.",
    "paragraphs": [
      "Brutal pain, living through it, and sometimes only its phantoms and inventions — that's what most often shapes the strongest works of art. It seems the important things are often born out of an endless struggle with yourself and self-reflection — but it needs saying, over and over again, because you can't always keep it all in. You need an emergency exit, somewhere you can stumble into and, just once, walk a slightly different path.",
      "To hear the seagulls' cry and, if only for a moment, drown out the endless whining about a better life that never ends — and it doesn't get easier for that, you still have to keep fighting it and moving forward, because you won't let yourself off the hook, you can't outrun yourself. Sooner or later it all catches up with you, and it's not clear whether that makes things any better.",
      "One thing is certain: you need to act. And if anyone still hasn't read Chekhov — read him at least once, might work as well as a sedative. Or you could watch Rimas Tuminas's Uncle Vanya. It became a classic of the theatrical canon long ago, even though it's been ten years since the premiere and its devices already read as archaic in places — but somehow it still works.",
      "Even on video, even with camera work that isn't always great, I didn't expect I'd end up in tears before the finale — that favourite, if slightly frightening, feeling of catharsis, when between acts you're pulled back to the mundane for a couple of minutes and feel an unexplainable shiver.",
      "If you want to see something worth your time beyond and above Butusov, to take one more look at a certain mad Lithuanian who brought at least one stunning actress to the stage — Zhenya Kregzhde — it's worth trying. And after that, who's still going to claim film beats theatre?",
    ],
    "meta": "Uncle Vanya (dir. Rimas Tuminas, Vakhtangov Theatre).",
    "link_label": None,
  },
  {
    "slug": "mauzer-terzopulos",
    "title": "Theodoros Terzopoulos's Mauser — Theatre of the Body, Live",
    "kicker": "The Alexandrinsky streamed the premiere online, and it turned my whole idea of theatre on video 180 degrees around. I understood maybe twenty percent, and that was enough.",
    "paragraphs": [
      "Thank god I didn't end up complaining about broadcasts lacking immersion or engagement. Today the Alexandrinsky streamed Theodoros Terzopoulos's premiere live, and it turned my whole idea of theatre on video 180 degrees around.",
      "Beautiful close-ups, an unusual, breath-driven way of the actors existing on stage — I can't imagine how they pulled it off, but you barely needed to follow what they were saying: some invisible force keeps your attention locked to the screen.",
      "Curious how this would land in the actual room — because right now my understanding sits at maybe twenty percent, and I've still got a lot of decoding ahead to unpack all the meanings in this Greek phenomenon. At first I was skeptical when Terzopoulos, in interviews, praised what's essentially actor-driven theatre — but this is really more a theatre of the body, of its possibilities and its beauty. It's worth shedding any prejudice about the male or female body being crude: it's simply an instrument, one some people know how to use, while everyone else should probably just walk past with their conservative reservations.",
      "I'm not ready to speak in detail about the meanings yet — I'll just note one favourite, Marton: he's excellent, impossible to look away from. The cast leans heavily male, the show is unbearably light on its feet, and despite the difficult subject of revolution, it handles it with surprising vitality. Strangely enough, you can feel the form here — without it, theatre is no good at all, whatever those insisting on purely narrative spectacle as the foundation of Russian culture might say.",
    ],
    "meta": "Theodoros Terzopoulos's Mauser, premiered live on the Alexandrinsky Theatre's stream.",
    "link_label": None,
  },
  {
    "slug": "shum-antishum-voronovskiy",
    "title": "Noise and Anti-Noise — a Lecture by Evgeny Voronovsky That Took Time to Sink In",
    "kicker": "On the physics of sound turned into a form of art — and on a space that can't simply be downloaded: only let in and felt.",
    "paragraphs": [
      "You've probably felt it: it's gotten too noisy in and around the window, all this junk spilling out well past its edges — as if we'd been deliberately stirred up so we wouldn't relax, so we'd stop for a second and think. But no — all we seem able to do is move it all online, running endless discussions about nothing, cutting ourselves off with an emoji at the end.",
      "Time to finally post this. The lecture happened back in January, but the need to talk about it only arrived now — it feels important to understand how much this whole stream affects us; what to do about it, how to protect yourself, none of that is clear either, everyone has to decide for themselves.",
      "Evgeny Voronovsky, the lecturer, told us some fairly straightforward physics — the kind of stuff sound-school students probably already know. But the whole thing came together into an entire world, took on the form of art: complex and simple things combined into something that wasn't a dull monologue on a set topic, but a joy in knowledge, a genuine delight in what you were hearing.",
      "All of this happened thanks to an educational project run as part of the Laboratory for the Contemporary Viewer, organized by musicAeterna's conductor Teodor Currentzis. Fast, with a few rough edges here and there, Teodor has managed to build a space for meaning, curiosity, and new knowledge in St. Petersburg — one you have to go looking for, making your way through the stern Soviet corridors of Dom Radio. You can't just download it off a computer — the only condition for taking it in is: let it in and feel it.",
      "Does it hurt?",
    ],
    "meta": "Evgeny Voronovsky's lecture as part of the Laboratory for the Contemporary Viewer (Dom Radio).",
    "link_label": "musicAeterna programme",
  },
]

MANIFESTO_POINTS_EN = [
  "Organized Culturality is a free space whose forms and formats are deeply unpredictable — as, indeed, are the topics one feels like discussing.",
  "The author isn't setting out to entertain, distract, or recommend. The only thing that matters in choosing material is the emotion behind it.",
  "Since Organized Culturality publishes texts, your reaction to them matters a great deal.",
  "Sometimes you'll want to share something on Culturality's other social channels — the full list can always be found in the profile.",
  "Without any reaction, everything will certainly go on living just fine, but sometimes it's nice to feel that someone needed to be here. Please don't be stingy with a simple like, or maybe a comment.",
  "Constructive criticism and proposals for collaboration are welcome too. Just remember: the author takes everything close to heart — don't overdo it with insults or advertising.",
  "Insults and bullying are absolutely unacceptable in this space. By nature the author isn't inclined toward stoking hostility or conflict — let's try not to push things that far. Wartime skirmishes over anything and nothing are especially forbidden here. In case of any disagreement, please leave this space without a scene.",
]

CV_ROLES_EN = [
    {
        "role": "Co-founder & Producer", "org": "AELITA PRODUCTION",
        "period": "June 2025 — present",
        "bullets": [
            "Launched a production company from scratch; over 10 completed projects within less than a year",
            "Producer of the Tochka Kyuri festival (Stary Oskol, October 2026)",
            "Developed the brand identity, full website, and a Telegram bot; runs SMM across four platforms",
        ],
    },
    {
        "role": "SMM", "org": "Komnata Sveta",
        "period": "January 2022 — present",
        "bullets": [
            "SMM for the theatre company Komnata Sveta — productions by the Yuri Butusov workshop",
            "Organizer of BuFest 2026 — a theatre festival at the Skorokhod venue (August 10–15)",
            "Ran the release of ZAVIST' (dir. Sofia Nikiforova) — sold out, wide interest from the professional community",
            "Organized regular touring shows of the Butusov workshop in St. Petersburg: every performance sold out",
        ],
    },
    {
        "role": "SMM, Project Manager", "org": "Scientific & Technological Theatre",
        "period": "May 2021 — present",
        "bullets": [
            "SMM for Russia's first robotic theatre — nominated for the Golden Mask (Experiment category)",
            "Performances at the New Stage of the Alexandrinsky Theatre, Sevkabel, Planetarium No. 1, MMOMA, and other venues",
            "Innovative projects in partnership with public and commercial venues in Moscow and St. Petersburg",
        ],
    },
    {
        "role": "Producer", "org": "Sofia Nikiforova, Sole Proprietor",
        "period": "2021 — 2022",
        "bullets": ["An educational project at the intersection of film and theatre within a commercial structure"],
    },
    {
        "role": "SMM", "org": "Svoboda Self-Portrait Studio",
        "period": "", "bullets": ["SMM for one of St. Petersburg's most distinctive photo studios"],
    },
    {
        "role": "SMM & PR", "org": "Novyy Vyatich",
        "period": "", "bullets": ["SMM and PR for Kaluga's leading souvenir brand"],
    },
]

PROJECTS_EN = [
  {
    "slug": "aelita-production",
    "role": "Co-founder & Producer",
    "period": "June 2025 — present",
    "title": "AELITA PRODUCTION",
    "kicker": "A production company launched from scratch — over ten completed projects within less than a year.",
    "facts": [("10+", "projects in a year"), ("2025", "year founded")],
    "paragraphs": [
      "AELITA PRODUCTION is a production company I founded in June 2025. In less than a year: over ten completed projects, from festivals to brand identities and websites for theatre companies.",
      "Among the company's projects: producing the Tochka Kyuri festival in Stary Oskol, developing a brand and a full website, including Telegram bots, and running SMM simultaneously across several platforms for several projects.",
      "AELITA PRODUCTION also partners with the dance company Korоche — organizing screenings, tours, and promotion for its shows.",
    ],
    "link_label": "aelita-production.ru",
  },
  {
    "slug": "bufest",
    "role": "Festival Organizer",
    "period": "August 2026",
    "title": "BuFest",
    "kicker": "A St. Petersburg theatre festival named after Yuri Butusov — three productions by his students over six evenings at the Skorokhod venue.",
    "facts": [("3", "productions"), ("6", "evenings"), ("Aug 10–15", "dates")],
    "paragraphs": [
      "BuFest is a St. Petersburg theatre festival named after Yuri Butusov, director at the Lensoviet and Vakhtangov theatres. Organized by the theatre company Komnata Sveta, hosted at Skorokhod (Moskovsky Ave, 107, bldg. 5).",
      "The main programme features three productions staged by Butusov's students: Viy. Speculations (dir. Alexander Tserenya), The Cherry Orchard (dir. Egor Kovalev), and The Seagull (dir. Ilya Zaitsev). Each show is performed twice in a row, without intermission, at 8 PM.",
      "Alongside the performances runs a special programme, 'BuFet': a photo exhibition by Yulia Smelkina on Butusov's rehearsals and behind-the-scenes life, a walking tour with Darya Pavlenko through 'Butusov's Petersburg,' a conversation with Wang Chen, and a screening of Sofia Nikiforova's documentary Chronicles of My Love.",
      "My role is organizing the festival as part of the Komnata Sveta team, where I've run SMM since January 2022.",
    ],
    "link_label": None,
  },
  {
    "slug": "tochka-kyuri",
    "role": "Festival Producer",
    "period": "October 2026",
    "title": "Tochka Kyuri",
    "kicker": "A festival in Stary Oskol produced by AELITA PRODUCTION.",
    "facts": [("Stary Oskol", "city"), ("Oct 2026", "dates")],
    "paragraphs": [
      "Tochka Kyuri is a festival in Stary Oskol produced by AELITA PRODUCTION. A full programme description will appear here closer to the event — for now the page is updated as materials become ready.",
    ],
    "link_label": None,
  },
  {
    "slug": "komnata-sveta",
    "role": "SMM",
    "period": "January 2022 — present",
    "title": "Komnata Sveta",
    "kicker": "A St. Petersburg theatre company — touring shows by the Yuri Butusov workshop, and BuFest, a festival in his memory.",
    "facts": [("2021", "first project"), ("2022", "work began")],
    "paragraphs": [
      "Komnata Sveta is a theatre company from St. Petersburg. The team's first project, in 2021, was the show ZAVIST', which won over audiences long before BuFest existed.",
      "In 2024 and 2025, Komnata Sveta brought touring shows by the Yuri Butusov workshop to St. Petersburg — both times to a warm reception. In 2026, the tour grew into a festival in his memory: BuFest.",
      "I've run the company's SMM since January 2022, including the run of ZAVIST' (dir. Sofia Nikiforova) — sold out, with broad interest from the professional community — and organizing the Butusov workshop's regular touring shows in the city.",
    ],
    "link_label": "Komnata Sveta on Telegram",
  },
  {
    "slug": "robot-kostya-project",
    "role": "SMM, Project Manager",
    "period": "May 2021 — present",
    "title": "Robot Kostya",
    "kicker": "Russia's first robotic theatre — a Golden Mask nominee in the Experiment category.",
    "facts": [("2021", "started"), ("Golden Mask", "nomination")],
    "paragraphs": [
      "Robot Kostya is a project of the Scientific & Technological Theatre, Russia's first theatre to feature a robot on stage. A production based on Chekhov's The Seagull, with the robot in one of the key roles.",
      "Nominated for the Golden Mask in the Experiment category. Performances have taken place on the New Stage of the Alexandrinsky Theatre, at Sevkabel Port, Planetarium No. 1, MMOMA, and at the Tochka Dostupa festival at the Lumière Hall in St. Petersburg.",
      "I've run SMM and management for the project since May 2021 — from performance announcements to coordinating innovative collaborations with public and commercial venues in Moscow and St. Petersburg.",
    ],
    "link_label": "Robot Kostya on Instagram",
  },
]

ABOUT_EN = {
    "title": "Konstantin Moshnikov",
    "bio": [
        "Over 15 years on stage — in circus, in theatre. I know the industry from the inside and understand its mechanics at every level.",
        "I produce and run SMM for cultural and art projects: from concept to launch, from marketing to logistics. Organized Culturality is a personal space alongside that work: texts about what struck a chord, with no obligation to convince anyone of anything.",
    ],
    "art_practice": "Circus performer · over 15 years. Currently in the operetta The Circus Princess at the St. Petersburg Musical Comedy Theatre (August and October 2026).",
}

